/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function BowlingPin(props) {
  const { nodes, materials } = useGLTF("/bowling_pin.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["BOWLING_PIN_Cube034-Mesh"].geometry}
        material={materials["Material.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["BOWLING_PIN_Cube034-Mesh_1"].geometry}
        material={materials["Material.009"]}
      />
    </group>
  );
}

useGLTF.preload("/bowling_pin.glb");
